### ISSUE TITLE
Immanuel Kant was not Russian :D

### ISSUE THREAD

**Issue by Maara1** [ybogdanov/history-timeline#22] opened 2016-02-14 17:44 UTC
He was Prussian and born in Königsberg. After the WW2 the city was taken and renamed by USSR, but it doesn't mean that Kant belongs to Russia.

**Comment by Maara1** [comment] 2016-02-14 17:47
Same with David Hilbert

**Comment by ybogdanov** [comment] 2016-02-15 20:20
Duplicate of https://github.com/ybogdanov/history-timeline/issues/19

**Closed as completed by ybogdanov** 2016-02-15 20:20 UTC
Labels: duplicate, content
